@echo off
REM Clean install + start dev server for Millenium Tech (Windows)
echo Removing any old/corrupted node_modules...
if exist node_modules rmdir /s /q node_modules
echo Installing dependencies from package-lock.json...
call npm ci
if errorlevel 1 (
  echo npm ci failed. Trying npm install...
  call npm install
)
echo Starting dev server...
call npm run dev
