# Generated by Django 6.1.1 on 2026-09-21 21:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference_number', models.CharField(db_index=True, editable=False, max_length=20, unique=True)),
                ('name', models.CharField(max_length=150)),
                ('phone', models.CharField(max_length=30)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('organization', models.CharField(blank=True, max_length=150)),
                ('project_type', models.CharField(choices=[('BUSINESS_WEBSITE', 'Business website'), ('WEB_APPLICATION', 'Web application'), ('SCHOOL_SYSTEM', 'School system'), ('CHURCH_SYSTEM', 'Church system'), ('ECOMMERCE', 'E-commerce'), ('BRANDING_DESIGN', 'Branding / design'), ('IT_SUPPORT', 'IT support'), ('PRODUCT_IDEA', 'Product / idea I need help shaping'), ('OTHER', 'Other custom solution')], default='OTHER', max_length=32)),
                ('problem_description', models.TextField(help_text='What problem are you trying to solve?')),
                ('desired_solution', models.TextField(blank=True, help_text='What would you like the solution to do?')),
                ('target_users', models.CharField(blank=True, help_text='Who will use it?', max_length=255)),
                ('current_approach', models.TextField(blank=True, help_text='How is this handled today, if at all?')),
                ('budget_range', models.CharField(blank=True, max_length=60)),
                ('timeline', models.CharField(blank=True, max_length=60)),
                ('additional_information', models.TextField(blank=True)),
                ('related_product', models.CharField(blank=True, max_length=80)),
                ('status', models.CharField(choices=[('NEW', 'New'), ('REVIEWING', 'Reviewing'), ('DISCOVERY', 'Discovery'), ('PROPOSAL', 'Proposal'), ('APPROVED', 'Approved'), ('BUILDING', 'Building'), ('TESTING', 'Testing'), ('LAUNCHED', 'Launched'), ('SUPPORT', 'Support'), ('REJECTED', 'Rejected'), ('ARCHIVED', 'Archived')], default='NEW', max_length=16)),
                ('priority', models.CharField(choices=[('LOW', 'Low'), ('NORMAL', 'Normal'), ('HIGH', 'High'), ('URGENT', 'Urgent')], default='NORMAL', max_length=8)),
                ('internal_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_project_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
